### PR TITLE
Handle require problems for webpack

### PR DESCRIPTION
**Pull request by perehnbom**
This PR is part of https://github.com/canjs/canjs/issues/2780

### CODE REVIEW

**Comment by matthewp** [comment]
Can you explain this change? What is require.resolve inside of webpack?

**Comment by perehnbom** [comment]
I described the problem in a comment in https://github.com/canjs/canjs/issues/2780

In can-fixture/fixture.js the following code is present:

```
if(typeof window !== "undefined" && !require.resolve) {
	window.fixture = fixture;
}
```

I believe it is there for test purposes, fixture is referenced directly in the tests. 

For some reason, having require.resolve gives an error when building and running with webpack, both in webpack 1 and 2, though I’m not quite sure why. Still, this change eliminates the problem. As described in the comment, I'll let you in the core team decide whether to use this PR or not, but at least it highlights the problem.

**Comment by matthewp** [comment]
No worries, just trying to think through it. Thanks for your contribution.

What error do you get without this change? Is there a WebPack build error that you can paste? Or a runtime error?

**Comment by perehnbom** [comment]
To highlight the problem, I have a test project, https://github.com/perehnbom/tryout-canjs3. So by cloning that and then run npm install && npm run build the problem is present.

When using webpack 1, the error logs are quite long and but Ill paste in the beginning of them. 

```
WARNING in ../~/can-fixture/fixture.js
Critical dependencies:
68:37-44 require function is used in a way in which dependencies cannot be statically extracted
 @ ../~/can-fixture/fixture.js 68:37-44

WARNING in ../~/can-fixture/package.json
Module parse failed: /Users/perehnbom/git/tryout-canjs3/node_modules/can-fixture/package.json Unexpected token (2:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:9)
    at Parser.pp$4.raise (/Users/perehnbom/git/tryout-canjs3/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/perehnbom/git/tryout-canjs3/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/Users/perehnbom/git/tryout-canjs3/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/Users/perehnbom/git/tryout-canjs3/node_modules/acorn/dist/acorn.js:966:10)

```

and

```
WARNING in ../~/can-fixture/README.md
Module parse failed: /Users/perehnbom/git/tryout-canjs3/node_modules/can-fixture/README.md Unexpected token (1:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:9)
    at Parser.pp$4.raise (/Users/perehnbom/git/tryout-canjs3/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/perehnbom/git/tryout-canjs3/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.expect (/Users/perehnbom/git/tryout-canjs3/node_modules/acorn/dist/acorn.js:597:28)
    at Parser.pp$3.parseExprList (/Users/perehnbom/git/tryout-canjs3/node_modules/acorn/dist/acorn.js:2152:16)
    at Parser.pp$3.parseExprAtom (/Users/perehnbom/git/tryout-canjs3/node_modules/acorn/dist/acorn.js:1801:28)
```

And quite many similar error printouts.

**Comment by matthewp** [comment]
Thanks, I think this change looks fine. I've also filed a bug with WebPack as I see no reason why this shouldn't be allowed: https://github.com/webpack/webpack/issues/3387

**Comment by perehnbom** [comment]
Thanks, yes it was a weird behaviour in webpack. I couldnt really figure out why it was a problem.

**Comment by matthewp** [comment]
This is released as 1.0.8

**Pull request merged**
