### PR TITLE
Set travis-ci to use node 4

### PR DESCRIPTION
**Pull request by ilyavf**

### CODE REVIEW

**Comment by daffl** [comment]
Why?

**Comment by ilyavf** [comment]
@daffl quote: @matthewp : "the latest which doesn't work with steal (yet) so change that to the version". So, should be 0.12

**Comment by daffl** [comment]
Ah yes. Let's set it to 4.x then.

**Comment by ilyavf** [comment]
@daffl, I squashed the commits. Node 4 works well.

**Pull request merged**
