### PR TITLE
Added support for making patch requests

### PR DESCRIPTION
**Pull request by julia-allyce**
Adds support for making patch requests. YAY!

### CODE REVIEW

**Comment by marshallswain** [comment]
:+1:

**Comment by BigAB** [comment]
:+1:

**Comment by justinbmeyer** [comment]
Looks good.  Regarding patch requests, do they return a body usually?  Would the response normally just be response headers?

**Comment by marshallswain** [comment]
I don' think the [spec](http://tools.ietf.org/html/rfc5789) has any requirements whether or not you return data during the PATCH response.  It does say that

> The server MUST apply the entire set of changes atomically and never
>    provide (e.g., in response to a GET during this operation) a
>    partially modified representation.

but that's more in reference to other requests coming in at the same time.

In the rest of the spec it seems more along the lines of "If you do return data, it's with a 200 response code.  If not, you send a 204.  And there are certain headers that you must send with a 200 response for caching."

**Comment by justinbmeyer** [comment]
Ah, I read HEAD when you wrote PATCH. Never mind.

**Pull request merged**
